import Foundation

/// Generates typed Swift client from Luxo schema introspection.
///
/// Usage:
///   let codegen = LuxoCodegen(endpoint: "http://localhost:4000/luvia", introspectionKey: "KEY")
///   try await codegen.generate(outputDir: "Sources/Generated", packageName: "LuxoGenerated")
///
/// Generates:
///   - Models.swift — Codable structs for all models
///   - Client.swift — Typed API methods with async/await
///   - SelectHints.swift — Pre-computed field hints (if analyze was run)
public final class LuxoCodegen {
    private let endpoint: String
    private let key: String

    public init(endpoint: String, introspectionKey: String) {
        self.endpoint = endpoint
        self.key = introspectionKey
    }

    /// Fetch schema and generate Swift files.
    public func generate(outputDir: String, packageName: String = "LuxoGenerated") async throws {
        // Fetch schema
        let schema = try await fetchSchema()

        let fm = FileManager.default
        try? fm.createDirectory(atPath: outputDir, withIntermediateDirectories: true)

        // Generate Models.swift
        let modelsCode = generateModels(schema)
        try modelsCode.write(toFile: "\(outputDir)/Models.swift", atomically: true, encoding: .utf8)

        // Generate Decoders.swift
        let decodersCode = generateDecoders(schema)
        try decodersCode.write(toFile: "\(outputDir)/Decoders.swift", atomically: true, encoding: .utf8)

        // Generate Schema.swift
        let schemaCode = generateSchema(schema)
        try schemaCode.write(toFile: "\(outputDir)/Schema.swift", atomically: true, encoding: .utf8)

        // Generate Client.swift
        let clientCode = generateClient(schema)
        try clientCode.write(toFile: "\(outputDir)/Client.swift", atomically: true, encoding: .utf8)

        print("[luxo] Generated Swift client → \(outputDir)/")
    }

    private func fetchSchema() async throws -> LuxoSchema {
        var request = URLRequest(url: URL(string: endpoint)!)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(key, forHTTPHeaderField: "X-Introspection-Key")
        request.httpBody = try JSONSerialization.data(withJSONObject: ["$api": "__schema"])

        let (data, _) = try await URLSession.shared.data(for: request)
        return try JSONDecoder().decode(LuxoSchema.self, from: data)
    }

    private func resolveFieldType(_ field: LuxoField, schema: LuxoSchema) -> String {
        let tn = field.typeName ?? field.type
        let isList = field.isList ?? false

        // Check enum
        if schema.enums?[tn] != nil { return isList ? "[\(tn)]" : tn }
        // Check model
        if schema.models[tn] != nil { return isList ? "[\(tn)]" : tn }
        // Check type decl
        if schema.types?[tn] != nil { return isList ? "[\(tn)]" : tn }

        let base = mapType(field.type, nullable: false, list: false)
        return isList ? "[\(base)]" : base
    }

    private func generateModels(_ schema: LuxoSchema) -> String {
        var out = "// GENERATED BY LuxoCodegen. DO NOT EDIT.\n\n"
        out += "import Foundation\n\n"

        // Enums — String-based enum
        if let enums = schema.enums {
            for (_, e) in enums.sorted(by: { $0.key < $1.key }) {
                out += "public enum \(e.name): String, Codable, Sendable, CaseIterable {\n"
                for v in e.values {
                    out += "    case \(v.lowercased()) = \"\(v)\"\n"
                }
                out += "}\n\n"
            }
        }

        // Type declarations (non-DB)
        if let types = schema.types {
            for (_, t) in types.sorted(by: { $0.key < $1.key }) {
                out += "public struct \(t.name): Codable, Sendable {\n"
                for field in t.fields {
                    let swiftType = resolveFieldType(field, schema: schema)
                    let nullable = field.nullable ?? false
                    out += "    public let \(field.name): \(nullable ? "\(swiftType)?" : swiftType)\n"
                }
                out += "}\n\n"
            }
        }

        // Models
        for (_, model) in schema.models.sorted(by: { $0.key < $1.key }) {
            out += "public struct \(model.name): Codable, Sendable {\n"
            for field in model.fields {
                let swiftType = resolveFieldType(field, schema: schema)
                let nullable = field.nullable ?? false
                out += "    public let \(field.name): \(nullable ? "\(swiftType)?" : swiftType)\n"
            }
            out += "}\n\n"
        }
        return out
    }

    private func generateClient(_ schema: LuxoSchema) -> String {
        var out = "// GENERATED BY LuxoCodegen. DO NOT EDIT.\n\n"
        out += "import Foundation\nimport LuxoClient\n\n"
        out += "public final class LuxoGeneratedClient {\n"
        out += "    private let transport: Transport\n"
        out += "    private var useBinary: Bool = false\n\n"
        out += "    public init(transport: Transport) {\n"
        out += "        self.transport = transport\n"
        out += "    }\n\n"
        out += "    /// Enable binary mode with schema registration.\n"
        out += "    public func enableBinary() {\n"
        out += "        useBinary = true\n"
        out += "        transport.setMode(.binary)\n"
        out += "        transport.setSchema(LUXO_SCHEMA)\n"
        out += "    }\n\n"

        for (_, api) in schema.apis.sorted(by: { $0.key < $1.key }) {
            let returnType = api.returnType ?? "Void"
            let swiftReturn = mapType(returnType, nullable: false, list: api.returnList ?? false)
            let hasModel = schema.models[returnType] != nil

            // Build params
            var paramList = ""
            var paramMap = ""
            if let params = api.params {
                let parts = params.map { p in
                    let t = mapType(p.type, nullable: !(p.required ?? true), list: false)
                    return "\(p.name): \(t)"
                }
                paramList = parts.joined(separator: ", ")
                paramMap = params.map { "\"\($0.name)\": \($0.name)" }.joined(separator: ", ")
            }

            out += "    public func \(api.name)(\(paramList)) async throws -> \(swiftReturn) {\n"
            if paramMap.isEmpty {
                out += "        let result = try await transport.call(\"\(api.name)\")\n"
            } else {
                out += "        let result = try await transport.call(\"\(api.name)\", params: [\(paramMap)])\n"
            }

            // Use binary decoder if model has a decoder function
            if hasModel {
                out += "        if useBinary, let rawData = result as? Data {\n"
                out += "            var decoder = Decoder(rawData)\n"
                if api.returnList ?? false {
                    out += "            return decoder.readArray { d in decode\(returnType)(&d) }\n"
                } else {
                    out += "            return decode\(returnType)(&decoder)\n"
                }
                out += "        }\n"
            }

            out += "        let data = try JSONSerialization.data(withJSONObject: result)\n"
            out += "        return try JSONDecoder().decode(\(swiftReturn).self, from: data)\n"
            out += "    }\n\n"
        }

        out += "}\n"
        return out
    }

    // MARK: - Binary Decoders

    private func generateDecoders(_ schema: LuxoSchema) -> String {
        var out = "// GENERATED BY LuxoCodegen. DO NOT EDIT.\n\n"
        out += "import Foundation\nimport LuxoClient\n\n"

        for (_, model) in schema.models.sorted(by: { $0.key < $1.key }) {
            out += "public func decode\(model.name)(_ decoder: inout Decoder) -> \(model.name) {\n"

            // Declare variables for each field with defaults
            for field in model.fields {
                let swiftType = resolveFieldType(field, schema: schema)
                let nullable = field.nullable ?? false
                let defaultVal = defaultValue(type: field.type, nullable: nullable, isList: field.isList ?? false)
                if nullable {
                    out += "    var _\(field.name): \(swiftType)? = \(defaultVal)\n"
                } else {
                    out += "    var _\(field.name): \(swiftType) = \(defaultVal)\n"
                }
            }

            out += "    while true {\n"
            out += "        let fieldID = decoder.nextField()\n"
            out += "        if fieldID == 0 { break }\n"
            out += "        switch fieldID {\n"

            for field in model.fields {
                let nullable = field.nullable ?? false
                let readExpr = readExpression(type: field.type, nullable: nullable, isList: field.isList ?? false)
                out += "        case \(field.id):\n"
                out += "            _\(field.name) = \(readExpr)\n"
            }

            out += "        default:\n"
            out += "            break // Skip unknown field\n"
            out += "        }\n"
            out += "    }\n"

            // Construct return
            out += "    return \(model.name)(\n"
            let fieldInits = model.fields.map { "        \($0.name): _\($0.name)" }
            out += fieldInits.joined(separator: ",\n")
            out += "\n    )\n"
            out += "}\n\n"
        }

        return out
    }

    private func readExpression(type: String, nullable: Bool, isList: Bool) -> String {
        if isList {
            let itemRead = readExpression(type: type, nullable: false, isList: false)
            return "decoder.readArray { d in \(itemRead.replacingOccurrences(of: "decoder", with: "d")) }"
        }
        if nullable {
            switch type {
            case "Int": return "decoder.readIntPtr()"
            case "Float": return "decoder.readFloatPtr()"
            case "String": return "decoder.readStringPtr()"
            case "Boolean": return "decoder.readBoolPtr()"
            default: return "decoder.readStringPtr()"
            }
        }
        switch type {
        case "Int": return "decoder.readSvarint()"
        case "Float": return "decoder.readFixed64()"
        case "String": return "decoder.readString()"
        case "Boolean": return "decoder.readBool()"
        default: return "decoder.readString()"
        }
    }

    private func defaultValue(type: String, nullable: Bool, isList: Bool) -> String {
        if nullable { return "nil" }
        if isList { return "[]" }
        switch type {
        case "Int": return "0"
        case "Float": return "0.0"
        case "String": return "\"\""
        case "Boolean": return "false"
        case "DateTime": return "Date()"
        case "UUID": return "UUID()"
        default: return "\"\""
        }
    }

    // MARK: - Schema Map

    private func generateSchema(_ schema: LuxoSchema) -> String {
        var out = "// GENERATED BY LuxoCodegen. DO NOT EDIT.\n\n"
        out += "import Foundation\nimport LuxoClient\n\n"
        out += "public let LUXO_SCHEMA: [String: APISchema] = [\n"

        for (_, api) in schema.apis.sorted(by: { $0.key < $1.key }) {
            var paramsStr = "nil"
            if let params = api.params, !params.isEmpty {
                let paramItems = params.enumerated().map { (idx, p) in
                    "APISchema.ParamSchema(fieldID: \(idx + 1), name: \"\(p.name)\", type: \"\(p.type)\")"
                }
                paramsStr = "[\(paramItems.joined(separator: ", "))]"
            }
            out += "    \"\(api.name)\": APISchema(id: \(api.id), params: \(paramsStr)),\n"
        }

        out += "]\n"
        return out
    }

    private func mapType(_ type: String, nullable: Bool, list: Bool) -> String {
        let base: String
        switch type {
        case "Int": base = "Int"
        case "Float": base = "Double"
        case "String": base = "String"
        case "Boolean": base = "Bool"
        case "DateTime": base = "Date"
        case "Duration": base = "TimeInterval"
        case "UUID": base = "UUID"
        default: base = type
        }

        let result = list ? "[\(base)]" : base
        return nullable ? "\(result)?" : result
    }
}
