import XCTest
@testable import LuxoCompiler

final class SelectAnalyzerTests: XCTestCase {
    func testFieldNodeProducesCanonicalSortedSelection() {
        let root = FieldNode.root()
        root.addChild("name")
        root.addChild("comments").addChild("text")
        root.addChild("comments").addChild("author").addChild("id")
        root.addChild("id")

        XCTAssertEqual(root.maxDepth(), 3)
        XCTAssertEqual(root.toSelectString(), "comments{author{id},text},id,name")
    }

    func testAnalyzerTracksDirectNestedAliasAndCollectionAccess() {
        let analyzer = SelectAnalyzer()
        analyzer.analyzeSource(
            """
            func load(client: Client) async throws {
                let user = try await client.getUser(id: 7)
                print(user.name)
                print(user.profile.email)
                let profile = user.profile
                print(profile.avatarURL)
                user.posts.forEach { post in
                    print(post.author.name)
                }
                print(user.comments[0].text)
            }
            """
        )

        XCTAssertEqual(
            analyzer.buildHints(),
            [
                "getUser": "comments{text},name,posts{author{name}},profile{avatarURL,email}"
            ]
        )
    }

    func testAnalyzerTracksFieldsThroughSelectedValueAccess() {
        let analyzer = SelectAnalyzer()
        analyzer.analyzeSource(
            """
            func load(client: Client) async throws {
                let user = try await client.getUser(id: 7)
                print(try user.name.requireValue())
                try user.posts.requireValue().forEach { post in
                    print(try post.title.requireValue())
                }
            }
            """
        )

        XCTAssertEqual(analyzer.buildHints(), ["getUser": "name,posts{title}"])
    }

    func testAnalyzerMergesAccessesAcrossSources() {
        let analyzer = SelectAnalyzer()
        analyzer.analyzeSource(
            """
            let user = await client.getUser()
            print(user.id)
            """
        )
        analyzer.analyzeSource(
            """
            let order = await client.getOrder()
            print(order.total)
            """
        )

        XCTAssertEqual(
            analyzer.buildHints(),
            [
                "getOrder": "total",
                "getUser": "id",
            ])
    }

    func testAnalyzerDoesNotLeakLocalBindingsAcrossSources() {
        let analyzer = SelectAnalyzer()
        analyzer.analyzeSource(
            """
            let user = await client.getUser()
            print(user.id)
            """
        )
        analyzer.analyzeSource("print(user.secret)")

        XCTAssertEqual(analyzer.buildHints(), ["getUser": "id"])
    }

    func testAnalyzerIgnoresUntrackedExpressions() {
        let analyzer = SelectAnalyzer()
        analyzer.analyzeSource(
            """
            print(local.value)
            let value = 42
            let copy = local.field
            """
        )

        XCTAssertTrue(analyzer.buildHints().isEmpty)
    }

    func testGeneratedHintsFileIsStableAndValidSwift() {
        let analyzer = SelectAnalyzer()
        analyzer.analyzeSource(
            """
            let z = await client.zeta()
            print(z.value)
            let a = await client.alpha()
            print(a.id)
            """
        )

        XCTAssertEqual(
            analyzer.generateHintsFile(),
            """
            // GENERATED BY LuxoAnalyze. DO NOT EDIT.

            import Foundation

            public enum SelectHints {
                public static let hints: [String: String] = [
                    "alpha": "id",
                    "zeta": "value",
                ]
            }

            """
        )
    }
}
