import Foundation
import SwiftSyntax
import SwiftParser

/// Compile-time field access analyzer using SwiftSyntax AST.
///
/// Tracks nested field access patterns on LuxoClient API responses:
///   post.user.name          → "user{name}"
///   post.comments[0].content → "comments{content}"
///   post.comments.forEach { $0.user.id } → "comments{user{id}}"
///
/// Run as build phase:
///   swift run LuxoAnalyze --source-dir Sources/ --output Sources/Generated/SelectHints.swift
public final class SelectAnalyzer: SyntaxVisitor {

    /// API name → field tree
    private var trees: [String: FieldNode] = [:]

    /// Variable name → API name
    private var varToAPI: [String: String] = [:]

    /// Variable name → parent source (for alias/closure tracking)
    private var varToParent: [String: (parentVar: String, field: String)] = [:]

    public static let maxNestingDepth = 5

    public init() {
        super.init(viewMode: .sourceAccurate)
    }

    // MARK: - Public API

    /// Analyze a Swift source string.
    public func analyzeSource(_ source: String) {
        let tree = Parser.parse(source: source)
        walk(tree)
    }

    /// Analyze a Swift source file.
    public func analyzeFile(at path: String) throws {
        let source = try String(contentsOfFile: path, encoding: .utf8)
        analyzeSource(source)
    }

    /// Build select hints: API name → $select string.
    public func buildHints() -> [String: String] {
        var result: [String: String] = [:]
        for (api, tree) in trees {
            let depth = tree.maxDepth()
            if depth > Self.maxNestingDepth {
                print("[luxo] Warning: \(api) has \(depth)-level nested field selection (max recommended: \(Self.maxNestingDepth)). Consider restructuring your query.")
            }
            let selectStr = tree.toSelectString()
            if !selectStr.isEmpty {
                result[api] = selectStr
            }
        }
        return result
    }

    /// Generate SelectHints.swift source code.
    public func generateHintsFile() -> String {
        let hints = buildHints()
        var out = "// GENERATED BY LuxoAnalyze. DO NOT EDIT.\n\n"
        out += "import Foundation\n\n"
        out += "public enum SelectHints {\n"
        out += "    public static let hints: [String: String] = [\n"
        for (api, select) in hints.sorted(by: { $0.key < $1.key }) {
            out += "        \"\(api)\": \"\(select)\",\n"
        }
        out += "    ]\n"
        out += "}\n"
        return out
    }

    // MARK: - SyntaxVisitor overrides

    /// Track: let user = await client.getUser(1)
    public override func visit(_ node: VariableDeclSyntax) -> SyntaxVisitorContinueKind {
        for binding in node.bindings {
            guard let pattern = binding.pattern.as(IdentifierPatternSyntax.self),
                  let init_ = binding.initializer?.value else { continue }

            let varName = pattern.identifier.text

            // Unwrap await/try
            let expr = unwrapAwaitTry(init_)

            // Check if it's a method call on a client
            if let call = expr.as(FunctionCallExprSyntax.self),
               let member = call.calledExpression.as(MemberAccessExprSyntax.self) {
                let apiName = member.declName.baseName.text
                varToAPI[varName] = apiName
                trees[apiName] = trees[apiName] ?? FieldNode.root()
            }

            // Check if it's a member access alias: let author = post.user
            if let member = expr.as(MemberAccessExprSyntax.self) {
                let fieldName = member.declName.baseName.text
                if let base = member.base?.as(DeclReferenceExprSyntax.self) {
                    let parentVar = base.baseName.text
                    if varToAPI[parentVar] != nil || varToParent[parentVar] != nil {
                        varToParent[varName] = (parentVar: parentVar, field: fieldName)
                    }
                }
            }
        }
        return .visitChildren
    }

    /// Track: post.user.name (member access chains)
    public override func visit(_ node: MemberAccessExprSyntax) -> SyntaxVisitorContinueKind {
        let chain = extractChain(ExprSyntax(node))
        if chain.count >= 2 {
            processChain(chain)
        }
        return .visitChildren
    }

    /// Track: post.comments.forEach { item in item.user.name }
    public override func visit(_ node: FunctionCallExprSyntax) -> SyntaxVisitorContinueKind {
        // Check if it's a collection method: arr.forEach { ... }
        guard let member = node.calledExpression.as(MemberAccessExprSyntax.self) else {
            return .visitChildren
        }
        let methodName = member.declName.baseName.text
        let collectionMethods: Set<String> = [
            "forEach", "map", "filter", "compactMap", "flatMap",
            "first", "contains", "allSatisfy", "sorted",
        ]
        guard collectionMethods.contains(methodName) else { return .visitChildren }

        // Get the source: post.comments
        guard let base = member.base else { return .visitChildren }
        let sourceChain = extractChain(base)
        guard sourceChain.count >= 2 else { return .visitChildren }

        let rootVar = sourceChain[0]
        guard varToAPI[rootVar] != nil else { return .visitChildren }

        // Get closure param name
        let closureArg = node.arguments.first(where: { arg in
            arg.expression.is(ClosureExprSyntax.self)
        })
        let trailingClosure = node.trailingClosure

        let closure = closureArg?.expression.as(ClosureExprSyntax.self) ?? trailingClosure
        guard let closure = closure else { return .visitChildren }

        // Get param name (explicit or $0)
        var paramName = "$0"
        if let sig = closure.signature,
           let params = sig.parameterClause?.as(ClosureParameterClauseSyntax.self) {
            if let first = params.parameters.first {
                paramName = first.firstName.text
            }
        } else if let sig = closure.signature,
                  let shorthand = sig.parameterClause?.as(ClosureShorthandParameterListSyntax.self) {
            if let first = shorthand.first {
                paramName = first.name.text
            }
        }

        // Link param to source field
        let sourceField = sourceChain.last!
        varToParent[paramName] = (parentVar: rootVar, field: sourceField)

        return .visitChildren
    }

    // MARK: - Helpers

    private func unwrapAwaitTry(_ expr: ExprSyntax) -> ExprSyntax {
        if let await_ = expr.as(AwaitExprSyntax.self) {
            return unwrapAwaitTry(await_.expression)
        }
        if let try_ = expr.as(TryExprSyntax.self) {
            return unwrapAwaitTry(try_.expression)
        }
        return expr
    }

    /// Extract property chain: post.user.name → ["post", "user", "name"]
    private func extractChain(_ expr: ExprSyntax) -> [String] {
        var chain: [String] = []
        var current = expr

        while true {
            if let member = current.as(MemberAccessExprSyntax.self) {
                chain.insert(member.declName.baseName.text, at: 0)
                if let base = member.base {
                    current = base
                } else {
                    break
                }
            } else if let subscript_ = current.as(SubscriptCallExprSyntax.self) {
                // arr[0] → skip index, continue with arr
                current = subscript_.calledExpression
            } else if let ref = current.as(DeclReferenceExprSyntax.self) {
                chain.insert(ref.baseName.text, at: 0)
                break
            } else {
                break
            }
        }
        return chain
    }

    private func processChain(_ chain: [String]) {
        let rootVar = chain[0]
        let apiName: String
        let fieldChain: [String]

        if let api = varToAPI[rootVar] {
            apiName = api
            fieldChain = Array(chain.dropFirst())
        } else if let resolved = resolveParentChain(rootVar) {
            guard let api = varToAPI[resolved.rootVar] else { return }
            apiName = api
            fieldChain = resolved.fields + Array(chain.dropFirst())
        } else {
            return
        }

        guard let tree = trees[apiName] else { return }
        var node = tree
        for field in fieldChain {
            node = node.addChild(field)
        }
    }

    private func resolveParentChain(_ varName: String) -> (rootVar: String, fields: [String])? {
        var fields: [String] = []
        var current = varName
        var seen = Set<String>()

        while let parent = varToParent[current] {
            if seen.contains(current) { break }
            seen.insert(current)
            fields.insert(parent.field, at: 0)
            current = parent.parentVar
        }

        guard !fields.isEmpty else { return nil }
        return (rootVar: current, fields: fields)
    }
}
